#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_CLA_KineticShield_Arm_L

#include "Basic.hpp"

#include "ABP_CLA_KineticShield_Arm_L_classes.hpp"
#include "ABP_CLA_KineticShield_Arm_L_parameters.hpp"


namespace SDK
{

// Function ABP_CLA_KineticShield_Arm_L.ABP_CLA_KineticShield_Arm_L_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_CLA_KineticShield_Arm_L_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_CLA_KineticShield_Arm_L_C", "AnimGraph");

	Params::ABP_CLA_KineticShield_Arm_L_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function ABP_CLA_KineticShield_Arm_L.ABP_CLA_KineticShield_Arm_L_C.AnimNotify_ShieldActive
// (BlueprintCallable, BlueprintEvent)

void UABP_CLA_KineticShield_Arm_L_C::AnimNotify_ShieldActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_CLA_KineticShield_Arm_L_C", "AnimNotify_ShieldActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_CLA_KineticShield_Arm_L.ABP_CLA_KineticShield_Arm_L_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_CLA_KineticShield_Arm_L_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_CLA_KineticShield_Arm_L_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_CLA_KineticShield_Arm_L.ABP_CLA_KineticShield_Arm_L_C.ExecuteUbergraph_ABP_CLA_KineticShield_Arm_L
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_CLA_KineticShield_Arm_L_C::ExecuteUbergraph_ABP_CLA_KineticShield_Arm_L(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_CLA_KineticShield_Arm_L_C", "ExecuteUbergraph_ABP_CLA_KineticShield_Arm_L");

	Params::ABP_CLA_KineticShield_Arm_L_C_ExecuteUbergraph_ABP_CLA_KineticShield_Arm_L Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_CLA_KineticShield_Arm_L.ABP_CLA_KineticShield_Arm_L_C.OnTagAdded_307F32DD403063CDE6CEA981B22E133C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     Tag                                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UABP_CLA_KineticShield_Arm_L_C::OnTagAdded_307F32DD403063CDE6CEA981B22E133C(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_CLA_KineticShield_Arm_L_C", "OnTagAdded_307F32DD403063CDE6CEA981B22E133C");

	Params::ABP_CLA_KineticShield_Arm_L_C_OnTagAdded_307F32DD403063CDE6CEA981B22E133C Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_CLA_KineticShield_Arm_L.ABP_CLA_KineticShield_Arm_L_C.OnTagRemoved_307F32DD403063CDE6CEA981B22E133C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     Tag                                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UABP_CLA_KineticShield_Arm_L_C::OnTagRemoved_307F32DD403063CDE6CEA981B22E133C(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_CLA_KineticShield_Arm_L_C", "OnTagRemoved_307F32DD403063CDE6CEA981B22E133C");

	Params::ABP_CLA_KineticShield_Arm_L_C_OnTagRemoved_307F32DD403063CDE6CEA981B22E133C Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_CLA_KineticShield_Arm_L.ABP_CLA_KineticShield_Arm_L_C.UnHideMaterialSlots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<int32>                           LODs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<int32>                           Materials                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UABP_CLA_KineticShield_Arm_L_C::UnHideMaterialSlots(TArray<int32>& LODs, TArray<int32>& Materials)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_CLA_KineticShield_Arm_L_C", "UnHideMaterialSlots");

	Params::ABP_CLA_KineticShield_Arm_L_C_UnHideMaterialSlots Parms{};

	Parms.LODs = std::move(LODs);
	Parms.Materials = std::move(Materials);

	UObject::ProcessEvent(Func, &Parms);

	LODs = std::move(Parms.LODs);
	Materials = std::move(Parms.Materials);
}

}

