#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Component_Trigger

#include "Basic.hpp"

#include "BP_Component_Trigger_classes.hpp"
#include "BP_Component_Trigger_parameters.hpp"


namespace SDK
{

// Function BP_Component_Trigger.BP_Component_Trigger_C.Trigger
// (BlueprintCallable, BlueprintEvent)

void UBP_Component_Trigger_C::Trigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Component_Trigger_C", "Trigger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Component_Trigger.BP_Component_Trigger_C.Reset
// (BlueprintCallable, BlueprintEvent)

void UBP_Component_Trigger_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Component_Trigger_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Component_Trigger.BP_Component_Trigger_C.OnTriggerStateChange__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_Component_Trigger_C*          TriggerComp                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    Param_Triggered                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Component_Trigger_C::OnTriggerStateChange__DelegateSignature(class UBP_Component_Trigger_C* TriggerComp, bool Param_Triggered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Component_Trigger_C", "OnTriggerStateChange__DelegateSignature");

	Params::BP_Component_Trigger_C_OnTriggerStateChange__DelegateSignature Parms{};

	Parms.TriggerComp = TriggerComp;
	Parms.Param_Triggered = Param_Triggered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Component_Trigger.BP_Component_Trigger_C.OnRep_Triggered
// (BlueprintCallable, BlueprintEvent)

void UBP_Component_Trigger_C::OnRep_Triggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Component_Trigger_C", "OnRep_Triggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Component_Trigger.BP_Component_Trigger_C.ExecuteUbergraph_BP_Component_Trigger
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Component_Trigger_C::ExecuteUbergraph_BP_Component_Trigger(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Component_Trigger_C", "ExecuteUbergraph_BP_Component_Trigger");

	Params::BP_Component_Trigger_C_ExecuteUbergraph_BP_Component_Trigger Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Component_Trigger.BP_Component_Trigger_C.isTriggered
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Param_Triggered                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Component_Trigger_C::IsTriggered(bool* Param_Triggered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Component_Trigger_C", "isTriggered");

	Params::BP_Component_Trigger_C_IsTriggered Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Triggered != nullptr)
		*Param_Triggered = Parms.Param_Triggered;
}

}

