#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneGoblinSpawner

#include "Basic.hpp"

#include "BP_DroneGoblinSpawner_classes.hpp"
#include "BP_DroneGoblinSpawner_parameters.hpp"


namespace SDK
{

// Function BP_DroneGoblinSpawner.BP_DroneGoblinSpawner_C.ExecuteUbergraph_BP_DroneGoblinSpawner
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroneGoblinSpawner_C::ExecuteUbergraph_BP_DroneGoblinSpawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroneGoblinSpawner_C", "ExecuteUbergraph_BP_DroneGoblinSpawner");

	Params::BP_DroneGoblinSpawner_C_ExecuteUbergraph_BP_DroneGoblinSpawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroneGoblinSpawner.BP_DroneGoblinSpawner_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DroneGoblinSpawner_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroneGoblinSpawner_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

