#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DeploymentCutsceneCharacter_1

#include "Basic.hpp"

#include "BP_DeploymentCutsceneCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DeploymentCutsceneCharacter_1.BP_DeploymentCutsceneCharacter_1_C
// 0x0000 (0x15F0 - 0x15F0)
class ABP_DeploymentCutsceneCharacter_1_C final : public ABP_DeploymentCutsceneCharacter_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DeploymentCutsceneCharacter_1_C">();
	}
	static class ABP_DeploymentCutsceneCharacter_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DeploymentCutsceneCharacter_1_C>();
	}
};
static_assert(alignof(ABP_DeploymentCutsceneCharacter_1_C) == 0x000010, "Wrong alignment on ABP_DeploymentCutsceneCharacter_1_C");
static_assert(sizeof(ABP_DeploymentCutsceneCharacter_1_C) == 0x0015F0, "Wrong size on ABP_DeploymentCutsceneCharacter_1_C");

}

