#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExtractionRoyaleGameMode

#include "Basic.hpp"

#include "G01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ExtractionRoyaleGameMode.BP_ExtractionRoyaleGameMode_C
// 0x0008 (0x0698 - 0x0690)
class ABP_ExtractionRoyaleGameMode_C : public AGzExtractionRoyaleGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0690(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ExtractionRoyaleGameMode_C">();
	}
	static class ABP_ExtractionRoyaleGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ExtractionRoyaleGameMode_C>();
	}
};
static_assert(alignof(ABP_ExtractionRoyaleGameMode_C) == 0x000008, "Wrong alignment on ABP_ExtractionRoyaleGameMode_C");
static_assert(sizeof(ABP_ExtractionRoyaleGameMode_C) == 0x000698, "Wrong size on ABP_ExtractionRoyaleGameMode_C");
static_assert(offsetof(ABP_ExtractionRoyaleGameMode_C, DefaultSceneRoot) == 0x000690, "Member 'ABP_ExtractionRoyaleGameMode_C::DefaultSceneRoot' has a wrong offset!");

}

