#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NonAutoActivatableNiagaraComponent

#include "Basic.hpp"

#include "Niagara_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NonAutoActivatableNiagaraComponent.BP_NonAutoActivatableNiagaraComponent_C
// 0x0000 (0x0780 - 0x0780)
class UBP_NonAutoActivatableNiagaraComponent_C : public UNiagaraComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NonAutoActivatableNiagaraComponent_C">();
	}
	static class UBP_NonAutoActivatableNiagaraComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NonAutoActivatableNiagaraComponent_C>();
	}
};
static_assert(alignof(UBP_NonAutoActivatableNiagaraComponent_C) == 0x000010, "Wrong alignment on UBP_NonAutoActivatableNiagaraComponent_C");
static_assert(sizeof(UBP_NonAutoActivatableNiagaraComponent_C) == 0x000780, "Wrong size on UBP_NonAutoActivatableNiagaraComponent_C");

}

