#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Track_Monorail

#include "Basic.hpp"

#include "BP_Track_Monorail_classes.hpp"
#include "BP_Track_Monorail_parameters.hpp"


namespace SDK
{

// Function BP_Track_Monorail.BP_Track_Monorail_C.CreateTrack
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStaticMesh*                      TrackMesh                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    HiddenInGame                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Track_Monorail_C::CreateTrack(class UStaticMesh* TrackMesh, bool HiddenInGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Track_Monorail_C", "CreateTrack");

	Params::BP_Track_Monorail_C_CreateTrack Parms{};

	Parms.TrackMesh = TrackMesh;
	Parms.HiddenInGame = HiddenInGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Track_Monorail.BP_Track_Monorail_C.GetLocationTangentAtIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Spacing                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Tangent                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Track_Monorail_C::GetLocationTangentAtIndex(int32 Param_Index, double Spacing, struct FVector* Location, struct FVector* Tangent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Track_Monorail_C", "GetLocationTangentAtIndex");

	Params::BP_Track_Monorail_C_GetLocationTangentAtIndex Parms{};

	Parms.Param_Index = Param_Index;
	Parms.Spacing = Spacing;

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);

	if (Tangent != nullptr)
		*Tangent = std::move(Parms.Tangent);
}


// Function BP_Track_Monorail.BP_Track_Monorail_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Track_Monorail_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Track_Monorail_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

