#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ToxicSmokeComponent

#include "Basic.hpp"

#include "G01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ToxicSmokeComponent.BP_ToxicSmokeComponent_C
// 0x0000 (0x0258 - 0x0258)
class UBP_ToxicSmokeComponent_C final : public UGzToxicSmokeComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ToxicSmokeComponent_C">();
	}
	static class UBP_ToxicSmokeComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ToxicSmokeComponent_C>();
	}
};
static_assert(alignof(UBP_ToxicSmokeComponent_C) == 0x000008, "Wrong alignment on UBP_ToxicSmokeComponent_C");
static_assert(sizeof(UBP_ToxicSmokeComponent_C) == 0x000258, "Wrong size on UBP_ToxicSmokeComponent_C");

}

