#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ThrowableDefaultActor

#include "Basic.hpp"

#include "G01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ThrowableDefaultActor.BP_ThrowableDefaultActor_C
// 0x0000 (0x0378 - 0x0378)
class ABP_ThrowableDefaultActor_C final : public AGzProjectileGrenade
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ThrowableDefaultActor_C">();
	}
	static class ABP_ThrowableDefaultActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ThrowableDefaultActor_C>();
	}
};
static_assert(alignof(ABP_ThrowableDefaultActor_C) == 0x000008, "Wrong alignment on ABP_ThrowableDefaultActor_C");
static_assert(sizeof(ABP_ThrowableDefaultActor_C) == 0x000378, "Wrong size on ABP_ThrowableDefaultActor_C");

}

