#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_L_LK_CeilingLight_LampPendant_04

#include "Basic.hpp"

#include "BP_L_1Throw_1Bulb_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_L_LK_CeilingLight_LampPendant_04.BPC_L_LK_CeilingLight_LampPendant_04_C
// 0x0000 (0x0960 - 0x0960)
class ABPC_L_LK_CeilingLight_LampPendant_04_C final : public ABP_L_1Throw_1Bulb_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_L_LK_CeilingLight_LampPendant_04_C">();
	}
	static class ABPC_L_LK_CeilingLight_LampPendant_04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPC_L_LK_CeilingLight_LampPendant_04_C>();
	}
};
static_assert(alignof(ABPC_L_LK_CeilingLight_LampPendant_04_C) == 0x000010, "Wrong alignment on ABPC_L_LK_CeilingLight_LampPendant_04_C");
static_assert(sizeof(ABPC_L_LK_CeilingLight_LampPendant_04_C) == 0x000960, "Wrong size on ABPC_L_LK_CeilingLight_LampPendant_04_C");

}

