#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_MarkerPingPadding

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_MarkerPingPadding.E_MarkerPingPadding
// NumValues: 0x0004
enum class E_MarkerPingPadding : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	E_MAX                                    = 3,
};

}

