#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_DomeShield

#include "Basic.hpp"

#include "GA_DomeShield_classes.hpp"
#include "GA_DomeShield_parameters.hpp"


namespace SDK
{

// Function GA_DomeShield.GA_DomeShield_C.BP_OnRemoveAbility
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UGA_DomeShield_C::BP_OnRemoveAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "BP_OnRemoveAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DomeShield.GA_DomeShield_C.DetonateShield
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_DomeShield_C::DetonateShield()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "DetonateShield");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DomeShield.GA_DomeShield_C.ExecuteUbergraph_GA_DomeShield
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DomeShield_C::ExecuteUbergraph_GA_DomeShield(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "ExecuteUbergraph_GA_DomeShield");

	Params::GA_DomeShield_C_ExecuteUbergraph_GA_DomeShield Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DomeShield.GA_DomeShield_C.InitAbilityComponent
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_DomeShield_C::InitAbilityComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "InitAbilityComponent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DomeShield.GA_DomeShield_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_DomeShield_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DomeShield.GA_DomeShield_C.OnFinish_1DF5512242E7C95938B16494CEFF888F
// (BlueprintCallable, BlueprintEvent)

void UGA_DomeShield_C::OnFinish_1DF5512242E7C95938B16494CEFF888F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "OnFinish_1DF5512242E7C95938B16494CEFF888F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DomeShield.GA_DomeShield_C.OnGadgetDestroyed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DestroyedActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_DomeShield_C::OnGadgetDestroyed(class AActor* DestroyedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "OnGadgetDestroyed");

	Params::GA_DomeShield_C_OnGadgetDestroyed Parms{};

	Parms.DestroyedActor = DestroyedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DomeShield.GA_DomeShield_C.ReadAbilityConfig
// (Event, Protected, BlueprintEvent)

void UGA_DomeShield_C::ReadAbilityConfig()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "ReadAbilityConfig");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DomeShield.GA_DomeShield_C.SpawnDomeGadget
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_DomeShield_C::SpawnDomeGadget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DomeShield_C", "SpawnDomeGadget");

	UObject::ProcessEvent(Func, nullptr);
}

}

