#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_WeaponAim

#include "Basic.hpp"

#include "G01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_WeaponAim.GA_WeaponAim_C
// 0x0000 (0x05F8 - 0x05F8)
class UGA_WeaponAim_C final : public UGzGA_WeaponAim
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_WeaponAim_C">();
	}
	static class UGA_WeaponAim_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_WeaponAim_C>();
	}
};
static_assert(alignof(UGA_WeaponAim_C) == 0x000008, "Wrong alignment on UGA_WeaponAim_C");
static_assert(sizeof(UGA_WeaponAim_C) == 0x0005F8, "Wrong size on UGA_WeaponAim_C");

}

