#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Header_22

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Header_22.Header_22_C
// 0x0000 (0x01B0 - 0x01B0)
class UHeader_22_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Header_22_C">();
	}
	static class UHeader_22_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHeader_22_C>();
	}
};
static_assert(alignof(UHeader_22_C) == 0x000010, "Wrong alignment on UHeader_22_C");
static_assert(sizeof(UHeader_22_C) == 0x0001B0, "Wrong size on UHeader_22_C");

}

