#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_ReportNavigationBtn

#include "Basic.hpp"

#include "G01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass S_ReportNavigationBtn.S_ReportNavigationBtn_C
// 0x0000 (0x07E0 - 0x07E0)
class US_ReportNavigationBtn_C final : public UGzCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"S_ReportNavigationBtn_C">();
	}
	static class US_ReportNavigationBtn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<US_ReportNavigationBtn_C>();
	}
};
static_assert(alignof(US_ReportNavigationBtn_C) == 0x000010, "Wrong alignment on US_ReportNavigationBtn_C");
static_assert(sizeof(US_ReportNavigationBtn_C) == 0x0007E0, "Wrong size on US_ReportNavigationBtn_C");

}

