#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapMarkerContainer

#include "Basic.hpp"

#include "WBP_MapMarkerContainer_classes.hpp"
#include "WBP_MapMarkerContainer_parameters.hpp"


namespace SDK
{

// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.ExecuteUbergraph_WBP_MapMarkerContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MapMarkerContainer_C::ExecuteUbergraph_WBP_MapMarkerContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "ExecuteUbergraph_WBP_MapMarkerContainer");

	Params::WBP_MapMarkerContainer_C_ExecuteUbergraph_WBP_MapMarkerContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.GetMarkerLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGzMarkerComponent*               MarkerComponent                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UWBP_MapMarkerContainer_C::GetMarkerLocation(const class UGzMarkerComponent* MarkerComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "GetMarkerLocation");

	Params::WBP_MapMarkerContainer_C_GetMarkerLocation Parms{};

	Parms.MarkerComponent = MarkerComponent;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.GetMarkerRotation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGzMarkerComponent*               MarkerComponent                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWBP_MapMarkerContainer_C::GetMarkerRotation(const class UGzMarkerComponent* MarkerComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "GetMarkerRotation");

	Params::WBP_MapMarkerContainer_C_GetMarkerRotation Parms{};

	Parms.MarkerComponent = MarkerComponent;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.GetRelativeLocalPlayerState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class APlayerState*                     OutPlayerState                                         (Parm, OutParm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UWBP_MapMarkerContainer_C::GetRelativeLocalPlayerState(class APlayerState** OutPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "GetRelativeLocalPlayerState");

	Params::WBP_MapMarkerContainer_C_GetRelativeLocalPlayerState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutPlayerState != nullptr)
		*OutPlayerState = Parms.OutPlayerState;
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.GetTeamAttitude
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           InPlayerState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// ETeamAttitude                           TeamAttitude                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MapMarkerContainer_C::GetTeamAttitude(class AActor* InPlayerState, ETeamAttitude* TeamAttitude)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "GetTeamAttitude");

	Params::WBP_MapMarkerContainer_C_GetTeamAttitude Parms{};

	Parms.InPlayerState = InPlayerState;

	UObject::ProcessEvent(Func, &Parms);

	if (TeamAttitude != nullptr)
		*TeamAttitude = Parms.TeamAttitude;
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.IsSupportingRotation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGzMarkerComponent*               MarkerComponent                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_MapMarkerContainer_C::IsSupportingRotation(const class UGzMarkerComponent* MarkerComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "IsSupportingRotation");

	Params::WBP_MapMarkerContainer_C_IsSupportingRotation Parms{};

	Parms.MarkerComponent = MarkerComponent;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.OnMarkerAdded
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UGzMarkerWidget*                  MarkerWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UGzMarkerComponent*               MarkerComponent                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MapMarkerContainer_C::OnMarkerAdded(class UGzMarkerWidget* MarkerWidget, class UGzMarkerComponent* MarkerComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "OnMarkerAdded");

	Params::WBP_MapMarkerContainer_C_OnMarkerAdded Parms{};

	Parms.MarkerWidget = MarkerWidget;
	Parms.MarkerComponent = MarkerComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.CalculatePlayerMarkerRotationForRemoteClient
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class AActor*                           InActor                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UWBP_MapMarkerContainer_C::CalculatePlayerMarkerRotationForRemoteClient(class AActor* InActor) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "CalculatePlayerMarkerRotationForRemoteClient");

	Params::WBP_MapMarkerContainer_C_CalculatePlayerMarkerRotationForRemoteClient Parms{};

	Parms.InActor = InActor;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.GetActorLocation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AActor*                           Actor                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_MapMarkerContainer_C::GetActorLocation(const class AActor* Actor) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "GetActorLocation");

	Params::WBP_MapMarkerContainer_C_GetActorLocation Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.GetActorRotation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AActor*                           Actor                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWBP_MapMarkerContainer_C::GetActorRotation(const class AActor* Actor) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "GetActorRotation");

	Params::WBP_MapMarkerContainer_C_GetActorRotation Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MapMarkerContainer.WBP_MapMarkerContainer_C.GetPlayerActorPositionFromMarker
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UWBP_MapMarkerContainer_C::GetPlayerActorPositionFromMarker(class UWidget* Widget) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapMarkerContainer_C", "GetPlayerActorPositionFromMarker");

	Params::WBP_MapMarkerContainer_C_GetPlayerActorPositionFromMarker Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

