#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BackpackPocket

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_BackpackPocket.WBP_BackpackPocket_C.SetCount
// 0x0018 (0x0018 - 0x0000)
struct WBP_BackpackPocket_C_SetCount final
{
public:
	int32                                         Count;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D53[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0010)()
};
static_assert(alignof(WBP_BackpackPocket_C_SetCount) == 0x000008, "Wrong alignment on WBP_BackpackPocket_C_SetCount");
static_assert(sizeof(WBP_BackpackPocket_C_SetCount) == 0x000018, "Wrong size on WBP_BackpackPocket_C_SetCount");
static_assert(offsetof(WBP_BackpackPocket_C_SetCount, Count) == 0x000000, "Member 'WBP_BackpackPocket_C_SetCount::Count' has a wrong offset!");
static_assert(offsetof(WBP_BackpackPocket_C_SetCount, CallFunc_Conv_IntToText_ReturnValue) == 0x000008, "Member 'WBP_BackpackPocket_C_SetCount::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

}

