#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Crosshair_Cyberlimbs_SmokeWall

#include "Basic.hpp"

#include "WBP_Crosshair_Cyberlimbs_SmokeWall_classes.hpp"
#include "WBP_Crosshair_Cyberlimbs_SmokeWall_parameters.hpp"


namespace SDK
{

// Function WBP_Crosshair_Cyberlimbs_SmokeWall.WBP_Crosshair_Cyberlimbs_SmokeWall_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Crosshair_Cyberlimbs_SmokeWall_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Crosshair_Cyberlimbs_SmokeWall_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Crosshair_Cyberlimbs_SmokeWall.WBP_Crosshair_Cyberlimbs_SmokeWall_C.ExecuteUbergraph_WBP_Crosshair_Cyberlimbs_SmokeWall
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Crosshair_Cyberlimbs_SmokeWall_C::ExecuteUbergraph_WBP_Crosshair_Cyberlimbs_SmokeWall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Crosshair_Cyberlimbs_SmokeWall_C", "ExecuteUbergraph_WBP_Crosshair_Cyberlimbs_SmokeWall");

	Params::WBP_Crosshair_Cyberlimbs_SmokeWall_C_ExecuteUbergraph_WBP_Crosshair_Cyberlimbs_SmokeWall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

