#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DynamicInventory

#include "Basic.hpp"

#include "WBP_DynamicInventory_classes.hpp"
#include "WBP_DynamicInventory_parameters.hpp"


namespace SDK
{

// Function WBP_DynamicInventory.WBP_DynamicInventory_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_DynamicInventory_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.ED_Item_New_Data__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGzInvItem                       NewItem                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_DynamicInventory_C::ED_Item_New_Data__DelegateSignature(const struct FGzInvItem& NewItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "ED_Item_New_Data__DelegateSignature");

	Params::WBP_DynamicInventory_C_ED_Item_New_Data__DelegateSignature Parms{};

	Parms.NewItem = std::move(NewItem);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.ExecuteUbergraph_WBP_DynamicInventory
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DynamicInventory_C::ExecuteUbergraph_WBP_DynamicInventory(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "ExecuteUbergraph_WBP_DynamicInventory");

	Params::WBP_DynamicInventory_C_ExecuteUbergraph_WBP_DynamicInventory Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.ItemButtonHover__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHover                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGzInvItem                       Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_DynamicInventory_C::ItemButtonHover__DelegateSignature(bool IsHover, const struct FGzInvItem& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "ItemButtonHover__DelegateSignature");

	Params::WBP_DynamicInventory_C_ItemButtonHover__DelegateSignature Parms{};

	Parms.IsHover = IsHover;
	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.OnButtonBaseHovered_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_DynamicInventory_C::OnButtonBaseHovered_Event(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "OnButtonBaseHovered_Event");

	Params::WBP_DynamicInventory_C_OnButtonBaseHovered_Event Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.OnButtonBaseUnhovered_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_DynamicInventory_C::OnButtonBaseUnhovered_Event(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "OnButtonBaseUnhovered_Event");

	Params::WBP_DynamicInventory_C_OnButtonBaseUnhovered_Event Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.OnPocketsUpdated
// (Event, Protected, BlueprintEvent)

void UWBP_DynamicInventory_C::OnPocketsUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "OnPocketsUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.OnPocketWidgetAdded
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UGzPocketWidget*                  PocketWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DynamicInventory_C::OnPocketWidgetAdded(class UGzPocketWidget* PocketWidget, int32 Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "OnPocketWidgetAdded");

	Params::WBP_DynamicInventory_C_OnPocketWidgetAdded Parms{};

	Parms.PocketWidget = PocketWidget;
	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DynamicInventory.WBP_DynamicInventory_C.OnPocketWidgetDataChanged_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGzInvItem                       NewItem                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_DynamicInventory_C::OnPocketWidgetDataChanged_Event(const struct FGzInvItem& NewItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DynamicInventory_C", "OnPocketWidgetDataChanged_Event");

	Params::WBP_DynamicInventory_C_OnPocketWidgetDataChanged_Event Parms{};

	Parms.NewItem = std::move(NewItem);

	UObject::ProcessEvent(Func, &Parms);
}

}

