#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BaseOpportunityMission

#include "Basic.hpp"

#include "UMG_classes.hpp"
#include "MissionGraphRuntime_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_BaseOpportunityMission.WBP_BaseOpportunityMission_C
// 0x0008 (0x02E8 - 0x02E0)
class UWBP_BaseOpportunityMission_C : public UUserWidget
{
public:
	class UMissionObjective*                      DisplayedObjective;                                // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void FindDeepestObjective(class UMissionObjective* In_Objective);
	void GetObjectiveTimeText(class FText* Text);
	void Set_Mission_Data(class AGzMission* Mission);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_BaseOpportunityMission_C">();
	}
	static class UWBP_BaseOpportunityMission_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BaseOpportunityMission_C>();
	}
};
static_assert(alignof(UWBP_BaseOpportunityMission_C) == 0x000008, "Wrong alignment on UWBP_BaseOpportunityMission_C");
static_assert(sizeof(UWBP_BaseOpportunityMission_C) == 0x0002E8, "Wrong size on UWBP_BaseOpportunityMission_C");
static_assert(offsetof(UWBP_BaseOpportunityMission_C, DisplayedObjective) == 0x0002E0, "Member 'UWBP_BaseOpportunityMission_C::DisplayedObjective' has a wrong offset!");

}

