#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingDetailView

#include "Basic.hpp"

#include "GameSettings_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SettingDetailView.WBP_SettingDetailView_C
// 0x0000 (0x03B8 - 0x03B8)
class UWBP_SettingDetailView_C final : public UGameSettingDetailView
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SettingDetailView_C">();
	}
	static class UWBP_SettingDetailView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SettingDetailView_C>();
	}
};
static_assert(alignof(UWBP_SettingDetailView_C) == 0x000008, "Wrong alignment on UWBP_SettingDetailView_C");
static_assert(sizeof(UWBP_SettingDetailView_C) == 0x0003B8, "Wrong size on UWBP_SettingDetailView_C");

}

