#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ZoneFillLayer

#include "Basic.hpp"

#include "G01_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ZoneFillLayer.WBP_ZoneFillLayer_C
// 0x0000 (0x02F8 - 0x02F8)
class UWBP_ZoneFillLayer_C final : public UGzZoneFillLayerWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ZoneFillLayer_C">();
	}
	static class UWBP_ZoneFillLayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ZoneFillLayer_C>();
	}
};
static_assert(alignof(UWBP_ZoneFillLayer_C) == 0x000008, "Wrong alignment on UWBP_ZoneFillLayer_C");
static_assert(sizeof(UWBP_ZoneFillLayer_C) == 0x0002F8, "Wrong size on UWBP_ZoneFillLayer_C");

}

